### ISSUE TITLE
Dataset Availiability

### ISSUE THREAD

**Issue by yogeshverma1998** [iclr2024submit/LT3P#1]
Hi,

Thanks for providing the code and fantastic work.

Can you let me know when the Physics Track dataset will be available that you have proposed in the paper?

**Comment by iclr2024submit** [comment]
Hello,

If you send an email to iclr2024submit@gmail.com, we will provide a description of the data and the data itself.

**Comment by QiXiLi** [comment]
Do you share the preprocessed data？
