### ISSUE TITLE
.npy inference and dataset

### ISSUE THREAD

**Issue by fresleven** [iclr2024submit/LT3P#2]
The inference doesn't work with the current UM data you gave, since there isn't any file with `z250_2019090500.npy` in the name. Also, when is the physics track dataset coming out?

**Comment by iclr2024submit** [comment]
Hi,

Please email us at iclr2024submit@gmail.com, and we will send you the data along with an explanation.

**Comment by QiXiLi** [comment]
Hi.Do you share the preprocessed data？
